/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testrecyclerview_MainActivity */

#ifndef _Included_com_example_testrecyclerview_MainActivity
#define _Included_com_example_testrecyclerview_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_testrecyclerview_MainActivity
 * Method:    testCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring

JNICALL Java_com_example_testrecyclerview_MainActivity_testCString
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
