/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hotupdatediff_DiffUtils */

#ifndef _Included_com_example_hotupdatediff_DiffUtils
#define _Included_com_example_hotupdatediff_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hotupdatediff_DiffUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_hotupdatediff_DiffUtils_diff
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
